# Generated by Django 2.2 on 2019-05-13 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='choice',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('etc1', models.CharField(max_length=50)),
                ('etc2', models.CharField(max_length=50)),
                ('etc3', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='join',
            fields=[
                ('email', models.CharField(max_length=100)),
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('nickname', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=200)),
                ('reg_date', models.DateField()),
            ],
        ),
    ]
